//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchProcessingEngine {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatchProcessingEngine.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; method must not have ref or out parameters. 的本地化字符串。
        /// </summary>
        internal static string Exception_InvokeDoesNotSupportRefOrOutParams {
            get {
                return ResourceManager.GetString("Exception_InvokeDoesNotSupportRefOrOutParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Multiple public &apos;{0}&apos; or &apos;{1}&apos; methods are available. 的本地化字符串。
        /// </summary>
        internal static string Exception_UseMiddleMutlipleInvokes {
            get {
                return ResourceManager.GetString("Exception_UseMiddleMutlipleInvokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Types that implement &apos;{0}&apos; do not support explicit arguments. 的本地化字符串。
        /// </summary>
        internal static string Exception_UseMiddlewareExplicitArgumentsNotSupported {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareExplicitArgumentsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; is not available. 的本地化字符串。
        /// </summary>
        internal static string Exception_UseMiddlewareIServiceProviderNotAvailable {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareIServiceProviderNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No public &apos;{0}&apos; or &apos;{1}&apos; method found for middleware of type &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Exception_UseMiddlewareNoInvokeMethod {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareNoInvokeMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No service for type &apos;{0}&apos; has been registered. 的本地化字符串。
        /// </summary>
        internal static string Exception_UseMiddlewareNoMiddlewareFactory {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareNoMiddlewareFactory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; or &apos;{1}&apos; does not return an object of type &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Exception_UseMiddlewareNonTaskReturnType {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareNonTaskReturnType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The &apos;{0}&apos; or &apos;{1}&apos; method&apos;s first argument must be of type &apos;{2}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Exception_UseMiddlewareNoParameters {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareNoParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &apos;{0}&apos; failed to create middleware of type &apos;{1}&apos;. 的本地化字符串。
        /// </summary>
        internal static string Exception_UseMiddlewareUnableToCreateMiddleware {
            get {
                return ResourceManager.GetString("Exception_UseMiddlewareUnableToCreateMiddleware", resourceCulture);
            }
        }
    }
}
